name = "porthouse.dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0aa914007b9d00ab00ce591795cbdc7bbb9e96ba9306ef5ab57a0202f3cae27e"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
datapack-folder = "global_packs/required_data"
