name = "porthouse.dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4530c7cab3ae3884ad6fb3a2d0f7e20e115b793e5403d7d8851f887ae710790d"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
datapack-folder = "global_packs/required_data"
