name = "porthouse.dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18c258e13907fa20e341486988d3ea88c250bbfe2d6753040ab95f694cea988d"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
datapack-folder = "global_packs/required_data"
