name = "porthouse.dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cd7fad9e0951b7b3df27da0524abb573377b3773eb912a0a66abd0074108365"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
datapack-folder = "global_packs/required_data"
